---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/juozasg/flux-client-perf.git

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flagger-podinfo
  namespace: default
spec:
  interval: 30s
  path: ./wge/podinfo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
