---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: podinfo
  namespace: test
spec:
  interval: 5m0s
  # url: https://stefanprodan.github.io/podinfo-bad
  url: https://stefanprodan.github.io/podinfo