---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 1s
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitrep
    namespace: default
  targetNamespace: default
